### ISSUE TITLE
Latest image install errors out, previous revision installs fine (FP2)

### ISSUE THREAD

**Issue by sarnold** [ubports/ubports-touch#56]
Which means ubuntu-device-flash --revision=N-1 is required, since without the revision arg it defaults to "latest".  I just tried 18 (fails) and then installed 17 (succeeds).  Trying the "diff" update from the phone worked just now, but failed when N was 3 and 2 was installed via the above flash command. OS Build Details now says "r18".

**Comment by NeoTheThird** [comment]
Can you check again? It should work now.

**Comment by sarnold** [comment]
Okay, sorry it took so long, but I'm still getting the same network error (connection reset by peer) with rc and devel, but now it happens for all builds, ie, using --revision=N for previous build no longer works.  It looks okay at the beginning downloading/pushing smaller files to the phone, but then it errors out at some point trying to download one of the bigger files (after around ~70 MBs or so).

**Comment by sarnold** [comment]
That was last night; today it just installed 15.04 devel r27 without a hiccup.  G o figure...

**Comment by sarnold** [comment]
That said, the console still shows something weird, even though it worked:

$ ubuntu-device-flash --server=http://system-image.ubports.com touch --channel=ubports-touch/15.04/devel --device=FP2
2017/06/15 15:02:52 Device is |FP2|
2017/06/15 15:02:53 Flashing version 27 from ubports-touch/15.04/devel channel and server http://system-image.ubports.com to device FP2
2017/06/15 15:02:53 Start pushing /home/sarnold/.cache/ubuntuimages/pool/keyring-4c4e7ef380ebcfa2c31084efa199138e93bfed8fc58aa3eb06bdf75a78af9b57.tar.xz to device
2017/06/15 15:02:53 Done pushing /home/sarnold/.cache/ubuntuimages/pool/keyring-4c4e7ef380ebcfa2c31084efa199138e93bfed8fc58aa3eb06bdf75a78af9b57.tar.xz to device
2017/06/15 15:02:53 Start pushing /home/sarnold/.cache/ubuntuimages/gpg/image-signing.tar.xz to device
2017/06/15 15:02:53 Start pushing /home/sarnold/.cache/ubuntuimages/ubports-touch/15.04/devel/FP2/version-27.tar.xz to device
993 B / 69.13 MB [________________________________________] 0.00 % 2.15 MB/s 31s2017/06/15 15:02:53 Start pushing /home/sarnold/.cache/ubuntuimages/gpg/image-master.tar.xz to device
2017/06/15 15:02:53 Done pushing /home/sarnold/.cache/ubuntuimages/gpg/image-signing.tar.xz to device
2017/06/15 15:02:53 Done pushing /home/sarnold/.cache/ubuntuimages/ubports-touch/15.04/devel/FP2/version-27.tar.xz to device
32.50 KB / 69.13 MB [_________________________________] 0.05 % 161.84 KB/s 7m17s2017/06/15 15:02:54 Done pushing /home/sarnold/.cache/ubuntuimages/gpg/image-master.tar.xz to device
69.13 MB / 69.13 MB [====================================] 100.00 % 113.48 KB/s 
2017/06/15 15:13:17 Start pushing /home/sarnold/.cache/ubuntuimages/pool/device-9c587dc2ba2182da5432e618e86efb9604f088448c2faab995afc1012b0adefe.tar.xz to device
75.24 MB / 321.93 MB [======>_______________________] 23.37 % 121.66 KB/s 34m36s2017/06/15 15:13:27 Done pushing /home/sarnold/.cache/ubuntuimages/pool/device-9c587dc2ba2182da5432e618e86efb9604f088448c2faab995afc1012b0adefe.tar.xz to device
321.93 MB / 321.93 MB [==================================] 100.00 % 231.11 KB/s 
2017/06/15 15:26:40 Start pushing /home/sarnold/.cache/ubuntuimages/pool/ubports-d50c18b27590af5734a826c4f7857d8909b0e0f902d21af142a780620c8eb58b.tar.xz to device
2017/06/15 15:27:25 Done pushing /home/sarnold/.cache/ubuntuimages/pool/ubports-d50c18b27590af5734a826c4f7857d8909b0e0f902d21af142a780620c8eb58b.tar.xz to device
2017/06/15 15:27:25 Created ubuntu_command: /home/sarnold/.cache/ubuntuimages/ubuntu_commands997992961
2017/06/15 15:27:25 Rebooting into recovery to flash
Failed to enter Recovery

**Comment by NeoTheThird** [comment]
I will leave this closed for now, since you said it worked for you. We'll keep an eye on this, though.

**Comment by sarnold** [comment]
r29 flash worked fine, and without the last "Failed to enter Recovery" message.

**Comment by NeoTheThird** [comment]
Let's file this one under expected unexpected behavior. Remember that computers are actually just carefully arranged sand.
